#开发环境配置文件
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xxxx
    password: xxxx
    url: jdbc:mysql://82.156.78.76:3307/xxxx?serverTimezone=UTC

logging:
  level:
    root: info
    cn.lcz: debug
  file:
    name: springlog/ams/ams.log
