#开发环境配置文件
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://82.156.78.75:3307/amsdb?serverTimezone=UTC

logging:
  level:
    root: info
    cn.lcz: debug
  file:
    name: springlog/ams/ams.log